# Generated by Django 4.1.1 on 2022-09-29 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='users',
            name='dev',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stacks', to='api.stack'),
        ),
        migrations.AlterUniqueTogether(
            name='users',
            unique_together={('dev', 'name')},
        ),
    ]
