# Generated by Django 4.1.1 on 2022-09-29 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_users_options_alter_users_dev_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='users',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stack',
            name='dev',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stacks', to='api.users'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='users',
            name='dev',
        ),
    ]
