# Generated by Django 4.1.1 on 2022-09-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_users_options_alter_users_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stack',
            old_name='dev',
            new_name='user',
        ),
    ]
