# Generated by Django 4.1.1 on 2022-09-29 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_dev_stack_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stack',
            name='user',
        ),
        migrations.AddField(
            model_name='users',
            name='dev',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stacks', to='api.stack'),
        ),
    ]
