# Generated by Django 4.1.1 on 2022-09-29 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_stack_user_users_dev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='dev',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.stack'),
        ),
    ]
